### PR TITLE
added a binary1 method for the metric calculation

### PR DESCRIPTION
**Pull request by ageller**
This allows us to use an existing metric for checking that all mentees have a mentor.

### CODE REVIEW

**Comment by agurvich** [comment]
Looking closer at this now, I think this change is not actually what we had in mind for fraction of mentees assigned mentors. What it looks like you have here is requiring that all _mentors_ are assigned a mentee (which is not the same as all _mentees_ are assigned a mentor). I think it is okay if we have mentors who end up not having anyone assigned to them whereas it is definitely not okay if there are mentees who are not assigned a mentor.

**Comment by agurvich** [comment]
but maybe you meant to have the option to discard networks that contained mentee-less mentors?

**Comment by ageller** [comment]
Hmm... I'll look at this tomorrow if I can.  I think the only change to the code here should be to add the binary1 option to the combined metric calculation.  (I had originally added a new metric in the first commit but then removed it during our meeting because it was redundant.)  But maybe the implementation of the binary1 in the colab notebook is wrong?  The idea would be to use this to eliminate any network where a mentee was not assigned any mentor.

**Comment by agurvich** [comment]
The diff makes it seem like you got rid of the function that was checking if every mentee got a mentor and added a binary1 option to the function that checks what fraction of mentors received a mentee. In my recent pushes I added a "constraint" to ensure that every mentee got a mentor so I think this PR might be redundant.

image

image

**Comment by ageller** [comment]
I'm not sure I'm following.  The binary1 part is in run_weighted_metrics (as a counterpart to binary0).  I'm not sure why the diff shows run_frac_mentors_assigned_mentees so prominently.  They're should be no change to that function from my PR.  This binary1 is meant to be available for all metrics.  I think it is still worth including regardless of the new constraint.

**Comment by agurvich** [comment]
Ah!!! You're right, the lines were elided, I clicked the arrows and it showed up correctly. Sorry about that.

**Pull request merged**
