### PR TITLE
bug fix alternative metric; avoided list->acceptable list; direct mat…

### PR DESCRIPTION
**Pull request by TStarkenburg**
- bug fix alternative mentors metric;
- name change mentors_avoided -> mentors_acceptable; 
- start of implementing direct matching based on mutual preferences before doing the first normal matching round (needs to be checked).

### CODE REVIEW

**Review by agurvich — APPROVED** [review]
nice catch on the paren for the metric fix. curious that you went nested loop brute force rather than looping through mentees and then just looping through their preferred mentors (if any) to see if the mentee appeared in their preferred mentees. Seems much more efficient. However, I am realizing now that the direct matching round could "fail" in a sense if a mentor prefers more mentees than they have capacity for (and all those mentees prefer them as well). In that scenario the ordering of the mentee list would determine who gets to be matched with that mentor.

**Comment by TStarkenburg** [comment]
Yeah sorry about the nested loop, I just wanted to do something quick and dirty to see what changes it made. In looking at the preferred metric having direct matching actually didn't help...
However, I figured checking whether someone is a mentee takes the same amount as right away checking if they have preferred mentors, and actually going from the mentors_prefr list you only have names, not Persons, so you then need to loop through the mentors anyway... So I though the double loop is not that much slower (one faster would be to check two people for mentee/mentor connection in both directions and then have one loop through all people and the second starting after the current Person).

**Comment by TStarkenburg** [comment]
O good. I don't often work with dictionaries. Now I can learn why I should :D

**Comment by agurvich** [comment]
😱🙀😱

**Pull request merged**
